services:
  # Angular Client Service
  client:
    build:
      context: ./angular-client
    ports:
      - "8080:80"
    networks:
      - app-network
    depends_on:
      - server

  # Node.js Server Service
  server:
    build:
      context: ./server
    ports:
      - "3000:3000"
    environment:
      - PGHOST=${PGHOST} 
      - PGPORT=${PGPORT}
      - PGUSER=${PGUSER}
      - PGPASSWORD=${PGPASSWORD}
      - PGDATABASE=${PGDATABASE}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - JWT_SECRET=${JWT_SECRET}
    networks:
      - app-network
    depends_on:
      - db 

  # PostgreSQL Database Service
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_DB: ${PGDATABASE}
    ports:
      - "5432:5432" 
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
